eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 9004
spring:
  application:
    name: ServiceClient2

# feign配置
feign: 
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true
